export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const CONFIRM_EMAIL = 'CONFIRM_EMAIL'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const FETCH_AUTH_USER = 'FETCH_AUTH_USER'
export const FETCH_AUTH_USER_SUCCESS = 'FETCH_AUTH_USER_SUCCESS'
export const FETCH_AUTH_USER_ERROR = 'FETCH_AUTH_USER_ERROR'

export const FETCH_ADDRESSES = 'FETCH_ADDRESSES'
export const FETCH_ADDRESSES_LOADING = 'FETCH_ADDRESSES_LOADING'
export const FETCH_ADDRESSES_SUCCESS = 'FETCH_ADDRESSES_SUCCESS'
export const FETCH_ADDRESSES_ERROR = 'FETCH_ADDRESSES_ERROR'

export const ADD_ADDRESS = 'ADD_ADDRESS'
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS'

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS'

export const DELETE_ADDRESS = 'DELETE_ADDRESS'
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'
export const DELETE_ADDRESS_ERROR = 'DELETE_ADDRESS_ERROR'
