export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const CONFIRM_EMAIL = 'CONFIRM_EMAIL'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const FETCH_AUTH_USER = 'FETCH_AUTH_USER'
export const FETCH_AUTH_USER_SUCCESS = 'FETCH_AUTH_USER_SUCCESS'
export const FETCH_AUTH_USER_ERROR = 'FETCH_AUTH_USER_ERROR'
